
Client -> RANCH SDK
Create archive <-> RANCHecker : RANCHecker
RANCH SDK -> Create archive
Create archive -> Submit Job
Submit Job <-> API : requests
API -> SWeb : requests
Sweb -> Render farme



RANCH SDK -> Download
Download  -> Get Finiched Job
Get Finiched Job <->  API : requests
RANCH SDK -> Connect api key
Connect api key <-> API